// VCP Skin Events and PLC I/O Mappings
// Extracted from Centroid ACORN PLC source code

export interface SkinEvent {
  id: number;
  name: string;
  displayName: string;
  description?: string;
}

export interface PlcInput {
  number: number;
  name: string;
  displayName: string;
}

export const SKIN_EVENTS: SkinEvent[] = [
  { id: 1, name: 'SkinSpinOverPlus_M', displayName: 'Spin Over Plus' },
  { id: 2, name: 'SkinSpinAutoMan_M', displayName: 'Spin Auto Man' },
  { id: 3, name: 'SkinAux1_M', displayName: 'Aux 1' },
  { id: 4, name: 'SkinAux2_M', displayName: 'Aux 2' },
  { id: 5, name: 'SkinAux3_M', displayName: 'Aux 3' },
  { id: 6, name: 'SkinSpin100_M', displayName: 'Spin 100%' },
  { id: 7, name: 'SkinSpinCW_M', displayName: 'Spin CW' },
  { id: 8, name: 'SkinAux4_M', displayName: 'Aux 4' },
  { id: 9, name: 'SkinAux5_M', displayName: 'Aux 5' },
  { id: 10, name: 'SkinAux6_M', displayName: 'Aux 6' },
  { id: 11, name: 'SkinSpinOverMinus_M', displayName: 'Spin Over Minus' },
  { id: 12, name: 'SkinSpinCCW_M', displayName: 'Spin CCW' },
  { id: 13, name: 'SkinAux7_M', displayName: 'Aux 7' },
  { id: 14, name: 'SkinAux8_M', displayName: 'Aux 8' },
  { id: 15, name: 'SkinAux9_M', displayName: 'Aux 9' },
  { id: 16, name: 'SkinSpinStop_M', displayName: 'Spin Stop' },
  { id: 17, name: 'SkinSpinStart_M', displayName: 'Spin Start' },
  { id: 18, name: 'SkinAux10_M', displayName: 'Aux 10' },
  { id: 19, name: 'SkinAux11_M', displayName: 'Aux 11' },
  { id: 20, name: 'SkinAux12_M', displayName: 'Aux 12' },
  { id: 21, name: 'SkinCoolAutoMan_M', displayName: 'Cool Auto Man' },
  { id: 22, name: 'SkinCoolFlood_M', displayName: 'Cool Flood' },
  { id: 23, name: 'SkinCoolMist_M', displayName: 'Cool Mist' },
  { id: 24, name: 'SkinVacOn_M', displayName: 'Vac On' },
  { id: 25, name: 'SkinLimitDefeat_M', displayName: 'Limit Defeat' },
  { id: 26, name: 'SkinIncCont_M', displayName: 'Inc Cont' },
  { id: 27, name: 'SkinX1_M', displayName: 'X1 Jog' },
  { id: 28, name: 'SkinX10_M', displayName: 'X10 Jog' },
  { id: 29, name: 'SkinX100_M', displayName: 'X100 Jog' },
  { id: 30, name: 'SkinMPG_M', displayName: 'MPG' },
  { id: 31, name: 'SkinJogAx4Plus_M', displayName: 'Jog Ax4 Plus' },
  { id: 32, name: 'SkinR7C2_M', displayName: 'R7C2' },
  { id: 33, name: 'SkinJogAx2Plus_M', displayName: 'Jog Ax2 Plus' },
  { id: 34, name: 'SkinR7C4_M', displayName: 'R7C4' },
  { id: 35, name: 'SkinJogAx3Plus_M', displayName: 'Jog Ax3 Plus' },
  { id: 36, name: 'SkinR8C1_M', displayName: 'R8C1' },
  { id: 37, name: 'SkinJogAx1Minus_M', displayName: 'Jog Ax1 Minus' },
  { id: 38, name: 'SkinFastSlowJog_M', displayName: 'Fast/Slow Jog' },
  { id: 39, name: 'SkinJogAx1Plus_M', displayName: 'Jog Ax1 Plus' },
  { id: 40, name: 'SkinR8C5_M', displayName: 'R8C5' },
  { id: 41, name: 'SkinJogAx4Minus_M', displayName: 'Jog Ax4 Minus' },
  { id: 42, name: 'SkinR9C2_M', displayName: 'R9C2' },
  { id: 43, name: 'SkinJogAx2Minus_M', displayName: 'Jog Ax2 Minus' },
  { id: 44, name: 'SkinR9C4_M', displayName: 'R9C4' },
  { id: 45, name: 'SkinJogAx3Minus_M', displayName: 'Jog Ax3 Minus' },
  { id: 46, name: 'SkinCycleCancel_M', displayName: 'Cycle Cancel' },
  { id: 47, name: 'SkinSingleBlock_M', displayName: 'Single Block' },
  { id: 48, name: 'SkinToolCheck_M', displayName: 'Tool Check' },
  { id: 49, name: 'SkinFeedHold_M', displayName: 'Feed Hold' },
  { id: 50, name: 'SkinCycleStart_M', displayName: 'Cycle Start' },
  { id: 51, name: 'SkinResetOk_M', displayName: 'Reset/OK' },
  { id: 52, name: 'SkinFeedOverMinus_M', displayName: 'Feed Over Minus' },
  { id: 53, name: 'SkinFeedOver100', displayName: 'Feed Over 100%' },
  { id: 54, name: 'SkinFeedOverPlus_M', displayName: 'Feed Over Plus' },
  { id: 55, name: 'KeepAlive_M', displayName: 'Keep Alive' },
  { id: 56, name: 'SkinResetButtonPressed_M', displayName: 'Reset Button Pressed' },
  { id: 58, name: 'OverrideRapidsEnabled_M', displayName: 'Override Rapids Enabled' },
  { id: 59, name: 'OverrideRapidsDisabled_M', displayName: 'Override Rapids Disabled' },
  { id: 60, name: 'VirtualJpRunning_M', displayName: 'Virtual JP Running' },
  { id: 61, name: 'UsingVirtualOverride_M', displayName: 'Using Virtual Override' },
  { id: 62, name: 'SkinResetSet_M', displayName: 'Reset Set' },
  { id: 63, name: 'FeedOverLT100', displayName: 'Feed Over < 100%' },
  { id: 64, name: 'FeedOverEQ100', displayName: 'Feed Over = 100%' },
  { id: 65, name: 'FeedOverGT100', displayName: 'Feed Over > 100%' },
  { id: 66, name: 'SkinAux13_M', displayName: 'Aux 13' },
  { id: 67, name: 'SkinAux14_M', displayName: 'Aux 14' },
  { id: 68, name: 'SkinAux15_M', displayName: 'Aux 15' },
  { id: 69, name: 'SkinAux16_M', displayName: 'Aux 16' },
  { id: 70, name: 'SkinTailStock_M', displayName: 'Tail Stock' },
  { id: 71, name: 'SkinOpenChuck_M', displayName: 'Open Chuck' },
  { id: 72, name: 'SkinCloseChuck_M', displayName: 'Close Chuck' },
  { id: 73, name: 'SkinWorklight_M', displayName: 'Work Light' },
  { id: 74, name: 'SkinColletOpenClose_M', displayName: 'Collet Open/Close' },
  { id: 75, name: 'SkinRouterAirBlow_M', displayName: 'Router Air Blow' },
  { id: 76, name: 'SkinSpindleHigh_M', displayName: 'Spindle High' },
  { id: 77, name: 'SkinSpindleMed_M', displayName: 'Spindle Med' },
  { id: 78, name: 'SkinSpindleLow_M', displayName: 'Spindle Low' },
  { id: 79, name: 'SkinSpindleBrake_M', displayName: 'Spindle Brake' },
  { id: 80, name: 'CncAndPlcActive_M', displayName: 'CNC and PLC Active' },
  { id: 81, name: 'DryRun_M', displayName: 'Dry Run' },
  { id: 82, name: 'RapidOver_M', displayName: 'Rapid Over' },
  { id: 83, name: 'SkinATCIndexPlus_M', displayName: 'ATC Index Plus' },
  { id: 84, name: 'SkinATCIndexMinus_M', displayName: 'ATC Index Minus' },
  { id: 85, name: 'SkinTurretIndex_M', displayName: 'Turret Index' },
  { id: 93, name: 'EStopPressed_M', displayName: 'E-Stop Pressed' },
  { id: 94, name: 'UsingKbOverride_M', displayName: 'Using KB Override' },
  { id: 99, name: 'SpinBrakeMode_M', displayName: 'Spin Brake Mode' },
  { id: 200, name: 'SkinManualLube_M', displayName: 'Manual Lube' },
  { id: 201, name: 'SkinClampOn_M', displayName: 'Clamp On' },
  { id: 202, name: 'SkinDustCollection_M', displayName: 'Dust Collection' },
  { id: 203, name: 'SkinCutoff_M', displayName: 'Cut Off' },
  { id: 204, name: 'SkinPartChute_M', displayName: 'Part Chute' },
  { id: 205, name: 'SkinToolUnclamp_M', displayName: 'Tool Unclamp' },
  { id: 206, name: 'SkinDustFoot_M', displayName: 'Dust Foot' },
  { id: 207, name: 'SkinLaserAlign_M', displayName: 'Laser Align' },
  { id: 208, name: 'SkinPopUpPins_M', displayName: 'Pop Up Pins' },
  { id: 209, name: 'SkinSpindleCooling_M', displayName: 'Spindle Cooling' },
];

export const PLC_INPUTS: PlcInput[] = [
  { number: 1057, name: 'SpinOverPlusKey', displayName: 'Spin Over Plus Key' },
  { number: 1058, name: 'SpinAutoManKey', displayName: 'Spin Auto/Man Key' },
  { number: 1059, name: 'Aux1Key', displayName: 'Aux 1 Key' },
  { number: 1060, name: 'Aux2Key', displayName: 'Aux 2 Key' },
  { number: 1061, name: 'Aux3Key', displayName: 'Aux 3 Key' },
  { number: 1062, name: 'SpinOver100Key', displayName: 'Spin Over 100% Key' },
  { number: 1063, name: 'SpinCWKey', displayName: 'Spin CW Key' },
  { number: 1064, name: 'Aux4Key', displayName: 'Aux 4 Key' },
  { number: 1065, name: 'Aux5Key', displayName: 'Aux 5 Key' },
  { number: 1066, name: 'Aux6Key', displayName: 'Aux 6 Key' },
  { number: 1067, name: 'SpinOverMinusKey', displayName: 'Spin Over Minus Key' },
  { number: 1068, name: 'SpinCCWKey', displayName: 'Spin CCW Key' },
  { number: 1069, name: 'Aux7Key', displayName: 'Aux 7 Key' },
  { number: 1070, name: 'Aux8Key', displayName: 'Aux 8 Key' },
  { number: 1071, name: 'Aux9Key', displayName: 'Aux 9 Key' },
  { number: 1072, name: 'SpinStopKey', displayName: 'Spin Stop Key' },
  { number: 1073, name: 'SpinStartKey', displayName: 'Spin Start Key' },
  { number: 1074, name: 'Aux10Key', displayName: 'Aux 10 Key' },
  { number: 1075, name: 'Aux11Key', displayName: 'Aux 11 Key' },
  { number: 1076, name: 'Aux12Key', displayName: 'Aux 12 Key' },
  { number: 1077, name: 'CoolAutoManKey', displayName: 'Cool Auto/Man Key' },
  { number: 1078, name: 'CoolFloodKey', displayName: 'Cool Flood Key' },
  { number: 1079, name: 'CoolMistKey', displayName: 'Cool Mist Key' },
  { number: 1080, name: 'VacOnKey', displayName: 'Vac On Key' },
  { number: 1081, name: 'LimitDefeatKey', displayName: 'Limit Defeat Key' },
  { number: 1082, name: 'IncrContKey', displayName: 'Incr/Cont Key' },
  { number: 1083, name: 'x1JogKey', displayName: 'X1 Jog Key' },
  { number: 1084, name: 'x10JogKey', displayName: 'X10 Jog Key' },
  { number: 1085, name: 'x100JogKey', displayName: 'X100 Jog Key' },
  { number: 1086, name: 'MPGKey', displayName: 'MPG Key' },
  { number: 1087, name: 'Ax4PlusJogKey', displayName: 'Ax4 Plus Jog Key' },
  { number: 1088, name: 'UnusedR7C2Key', displayName: 'Unused R7C2 Key' },
  { number: 1089, name: 'Ax2PlusJogKey', displayName: 'Ax2 Plus Jog Key' },
  { number: 1090, name: 'UnusedR7C4Key', displayName: 'Unused R7C4 Key' },
  { number: 1091, name: 'Ax3PlusJogKey', displayName: 'Ax3 Plus Jog Key' },
  { number: 1092, name: 'UnusedR8C1Key', displayName: 'Unused R8C1 Key' },
  { number: 1093, name: 'Ax1MinusJogKey', displayName: 'Ax1 Minus Jog Key' },
  { number: 1094, name: 'FastSlowKey', displayName: 'Fast/Slow Key' },
  { number: 1095, name: 'Ax1PlusJogKey', displayName: 'Ax1 Plus Jog Key' },
  { number: 1096, name: 'UnusedR8C5Key', displayName: 'Unused R8C5 Key' },
  { number: 1097, name: 'Ax4MinusJogKey', displayName: 'Ax4 Minus Jog Key' },
  { number: 1098, name: 'UnusedR9C2Key', displayName: 'Unused R9C2 Key' },
  { number: 1099, name: 'Ax2MinusJogKey', displayName: 'Ax2 Minus Jog Key' },
  { number: 1100, name: 'UnusedR9C4Key', displayName: 'Unused R9C4 Key' },
  { number: 1101, name: 'Ax3MinusJogKey', displayName: 'Ax3 Minus Jog Key' },
  { number: 1102, name: 'CycleCancelKey', displayName: 'Cycle Cancel Key' },
  { number: 1103, name: 'SingleBlockKey', displayName: 'Single Block Key' },
  { number: 1104, name: 'ToolCheckKey', displayName: 'Tool Check Key' },
  { number: 1105, name: 'FeedHoldKey', displayName: 'Feed Hold Key' },
  { number: 1106, name: 'CycleStartKey', displayName: 'Cycle Start Key' },
];

// Helper functions for dropdowns
export function getSkinEventById(id: number): SkinEvent | undefined {
  return SKIN_EVENTS.find(e => e.id === id);
}

export function getPlcInputByNumber(number: number): PlcInput | undefined {
  return PLC_INPUTS.find(i => i.number === number);
}
